### ISSUE TITLE
export models to ONNX

### ISSUE THREAD

**Issue by GotG** [hmorimitsu/ptlflow#26]
Hello

Do you have any suggestion/workflow on how to export the optical flow models to ONNX?

Thank you!

**Comment by hmorimitsu** [comment]
Hi,

Have you tried to follow the ONNX guide from PyTorch? I think it should work, although I am not sure if it can work for all models, as some of them may have some custom layers not supported by ONNX.

**Comment by GotG** [comment]
I loaded the models with ptlflow, then tried the conversion. unfortunately, none of the model conversions worked for me.

**Comment by hmorimitsu** [comment]
Hi,

I wrote a simple example to export to ONNX in this Colab: https://colab.research.google.com/drive/11xvIEerkxowM_lO-hEDNOqT6dANDZKUd?usp=sharing

Note, however, that it seems that ONNX does not support grid_sample at the moment, so many models cannot be exported, at least without changing their code.

**Comment by GotG** [comment]
Hello
Thank you, looks good! I managed to convert flownets as well using ptl method.
However the grid_sampler is a long running onnx support problem. Apparently it should be added to onnx (not pytorch yet) this November. Fingers crossed.
