### ISSUE TITLE
Inference on a whole video (or batch of image pairs) efficiently?

### ISSUE THREAD

**Issue by zplizzi** [hmorimitsu/ptlflow#28]
I would like to process a whole video efficiently - ie not calling model.forward() once for every pair of images, and instead batching things together. But I can't quite figure out how to do that with `IOAdapter ` (which I would like to use, to ensure eg I use the correct padding). Is this possible? I tried formatting my video into a batch of image pairs, of shape (batch, 2, h, w, c), but this didn't seem to be supported by `IOAdapter`.

**Comment by zplizzi** [comment]
Yeah, in an ideal world you'd have a method to automatically find the largest batch size that fits in memory (like they do in https://pytorch-lightning.readthedocs.io/en/latest/advanced/training_tricks.html#auto-scaling-of-batch-size), and chunk the video into that size for processing. But I agree that's probably overkill here. Probably just adding the above trick into the docs somewhere would be plenty.

**Comment by hmorimitsu** [comment]
Added a small section with a link to this issue in the inference docs in #29 .
