### ISSUE TITLE
EPE calculation 

### ISSUE THREAD

**Issue by GowthamInti** [hmorimitsu/ptlflow#43]
Hi I have run a validate.py on FlowNetS pre trained on things choosing validation dataset as things. The EPE is 12.96 which is very high. as per the paper the EPE has to be around 4-5. Is there any error in computing EPE or am I missing something?

I really appreciate any help you can provide.

I ran the validate.py with the following args

python validate.py flownets --pretrained_ckpt things  --val_dataset things

**Comment by hmorimitsu** [comment]
Hello, thank you for reporting.

I don't think there are problems with the EPE, since the overall results look OK.

There may be some problem with the model, but I'll have to check further.

Can you tell which paper reported these results?

Best
