### ISSUE TITLE
validation issue with checkpoints .pth format

### ISSUE THREAD

**Issue by nihalgupta84** [hmorimitsu/ptlflow#44]
I have pretrained checkpoints in .pth format.

during validation i am giving the path of /path/to/checkpoitns.pth 

but it shows unrecognized error.

**Comment by hmorimitsu** [comment]
Hi,

Could you provide more details about the error? What is the specific command you're running and what's the exact error message?

Best

**Comment by nihalgupta84** [comment]
thanks! solved this but have another issue with 

flownets model: while loading pre-trained checkpoints of {trained in chairs}, {trained in sintel} and {trained in kitti}

it thorugh model weights compatibility issue. I hope, this is the base model as prescribed in paper.

and where do i find the spynet model

**Comment by hmorimitsu** [comment]
Hi, please provide the exact command and error message so it's easier to identify the problem.

We unfortunately don't have spynet, so you will have to use another code for that model.

Best
