### ISSUE TITLE
query related to datasets splits and checkpoints

### ISSUE THREAD

**Issue by nihalgupta84** [hmorimitsu/ptlflow#45]
what's the difference between trainval and val?

how do i get the checkpoints information in more detail if training has been done in mixed datasets?

**Comment by hmorimitsu** [comment]
Hi,

trainval means train+val splits together.

About the checkpoints, they were converted from the official ones, so you should check the official repositories directly for more information. The sources for each checkpoint are at: https://ptlflow.readthedocs.io/en/latest/models/checkpoint_list.html

Best

**Comment by nihalgupta84** [comment]
thanks for the quick reply!
