### ISSUE TITLE
Difference inference result with and without using batch inference?

### ISSUE THREAD

**Issue by ZHAOZHIHAO** [hmorimitsu/ptlflow#48]
Hi, 

First thanks for your nice library.

I try to inference a batch like https://github.com/hmorimitsu/ptlflow/issues/28, but the result seems not aligned with no batch inference. My code for batch is as follows:

```
    # images: a list of numpy array in H,W,C
    io_adapter = IOAdapter(model, images[0].shape[:2])
    inputs = io_adapter.prepare_inputs(np.array(images))
    input_images = inputs["images"][0]
    video1 = input_images[:-1]
    video2 = input_images[1:]
    input_images = torch.stack((video1, video2), dim=1)
    inputs["images"] = input_images
    out = model(inputs)
    out = io_adapter.unpad_and_unscale(out)

```

Best

**Comment by hmorimitsu** [comment]
Hi, thanks for reporting.

Could you also show how you do the non-batch inference? I did a simple test and they give the same results, but maybe you are doing in a different way. Please try to provide a more complete example showing the difference.

Best,

**Comment by ZHAOZHIHAO** [comment]
Hi, yesterday I was testing with CPU. I'll test it with GPU and see if they are aligned. 

While using GPU, I found that the algorithm takes more than 32G memory if I test a batch of images in a sequential manner, which is unreasonable. And "with torch.no_grad():" solves this problem.

Best

**Comment by ZHAOZHIHAO** [comment]
Hi, here is the code for with and without using batch

```
def return_flow_multiple_image(model, images, batch):
    # images: a list of numpy array in H,W,C
    if batch:
        io_adapter = IOAdapter(model, images[0].shape[:2])
        inputs = io_adapter.prepare_inputs(np.array(images))
        input_images = inputs["images"][0].to("cuda")
        video1 = input_images[:-1]
        video2 = input_images[1:]
        input_images = torch.stack((video1, video2), dim=1)
        inputs["images"] = input_images
        with torch.no_grad():
            out = model(inputs)
        out = io_adapter.unpad_and_unscale(out)
        f_flows = out['flows'].squeeze()
        f_flows = [f_flows[i] for i in range(f_flows.shape[0])]
    else:
        io_adapter = IOAdapter(model, images[0].shape[:2])
        with torch.no_grad():
            f_flows = [return_flow_single_image(io_adapter, images[0], np.array(images[idx])) for idx in range(1, len(images))]
    return f_flows
```

Best

**Comment by ZHAOZHIHAO** [comment]
Hi,

I think the batch version should be correct. I had different input for batch and sequential before. 

Best
