### ISSUE TITLE
The loss function of LiteFlowNet*

### ISSUE THREAD

**Issue by ChenYizhenCN** [hmorimitsu/ptlflow#50]
Hi Henrique, thanks for this great repo!

I tried to train the model by running "!python train.py **liteflownet3**", as indicated in liteflownet3.py (with loss_fn=None), it will be reported that

" assert self.loss_fn is not None, f'Model {self.\_\_class\_\_. \_\_name__} cannot be trained.
It does not have loss function.' AssertionError: Model LiteFlowNet3 cannot be trained. it does not have loss function. "

However, L2 loss is used in training as mentioned in the liteflownet3 paper.

This means that liteflownet3 does not support training in ptlflow for now? And

would you have plans to add support for liteflownet3?

Thanks again for your great work.

**Comment by hmorimitsu** [comment]
Hello,

Unfortunately I don't have time to implement and test the loss functions
for the missing models for now.

If you want to implement the loss by yourself, don't forget liteflownet 3
also has an additional confidence map loss term.

Best.

**Comment by ChenYizhenCN** [comment]
Thank you for responding!

Many thanks for your generous contribution.

I gladly try to implement the loss and it will be first shared once progress has been made.

Best regards.
