### ISSUE TITLE
question about flow definition

### ISSUE THREAD

**Issue by Cai-RS** [hmorimitsu/ptlflow#72]
Hello, thanks for your job!
I want to know that, if the output of all the flow model is " coordinate of matching point in the latter image  -  coordinate of matching point in the latter image", (X_img2 - X_img1, Y_img2 - Y_img1)? Or is it the opposite calculation method（X_img1 - X_img2, Y_img1 - Y_img2)?

**Comment by nihalgupta84** [comment]
works both way, u just need to check bidrection flow available or not

**Comment by hmorimitsu** [comment]
Hello. 

The usual output (which is inside inputs["flows"], for example) is according to your first definition, which can also be written as coords_img2 = coords_img1 + flow. The opposite direction is stored as "flows_b" and is usually only available when the bidirectional flow is used, as mentioned by @nihalgupta84 .

Best.

**Comment by Cai-RS** [comment]
> Hello.
> 
> The usual output (which is inside inputs["flows"], for example) is according to your first definition, which can also be written as coords_img2 = coords_img1 + flow. The opposite direction is stored as "flows_b" and is usually only available when the bidirectional flow is used, as mentioned by @nihalgupta84 .
> 
> Best.

Get it! Thanks a lot!
