### ISSUE TITLE
Inconsistent Optical Flow Output Compared to Official RAFT

### ISSUE THREAD

**Issue by dd2912** [hmorimitsu/ptlflow#74]
First of all, thank you for the amazing work on this repository!

I'm encountering an issue where the optical flow results from this repo differ from those produced by the official RAFT implementation.  In both cases, I used Sintel checkpoints. 

Command used:
```bash
python infer.py raft --input_path ../video/frames/ --write_outputs --flow_format flo --output_path ../video/raft --pretrained_ckpt sintel
```
Input images:

![14000](https://github.com/user-attachments/assets/0a9fe851-3d03-4571-8a94-fbd666ebcbed)

![14002](https://github.com/user-attachments/assets/a67266f0-ef68-40c1-9d35-9a898e418aad)

Results:
Output from this repo:
![14000](https://github.com/user-attachments/assets/94b41f31-f75b-4293-b1c7-80265fc35bd6)

Output from official RAFT:
![00000](https://github.com/user-attachments/assets/3465e8ed-69e6-4715-8dac-b52cadb92355)

The results don't align, and I'm unsure what's causing the discrepancy.

Any insights or suggestions?

**Comment by hmorimitsu** [comment]
Hi, thanks for reporting.

I used your example on my machine and got the result below, which is still not the same as the official RAFT, but it seems close.

![img1_flow](https://github.com/user-attachments/assets/b9469522-e1b3-492f-86ff-8cb9d820b75e)

I am not sure what could be causing this problem for you. Can you check your package versions? I am using:

torch=2.2.2+cuda12.1
lightning=1.9.5

What resolution are your inputs? The images I downloaded are 360x640, but I don't know if this is the same resolution you are using.

This is what I can think of now, but please let me know if you find some new information.

Best

**Comment by dd2912** [comment]
I reinstalled the software, and it's working now. Thanks for looking into it!

P.S. The slight difference you observed is likely due to the low resolution of the input images. When I run it on the full resolution, the results are much more similar.

Thanks again!
