### ISSUE TITLE
Unable to Register an Account on the MPI Sintel Website  Body:

### ISSUE THREAD

**Issue by fangfang11-plog** [hmorimitsu/ptlflow#75]
I am encountering issues while trying to register an account for the MPI Sintel dataset. I have followed the website's instructions and sent an email containing my full name and affiliation to [sintel@tue.mpg.de](mailto:sintel@tue.mpg.de), but it has been over 12 hours and I still cannot access or download the dataset.

Here are the detailed steps I have taken to register:

I visited the official website of the MPI Sintel dataset: http://sintel.is.tue.mpg.de/.
I checked my email address and domain to confirm they were not enabled.
I sent an email as instructed by the website, including my full name and affiliation, to [sintel@tue.mpg.de](mailto:sintel@tue.mpg.de).
I have waited for more than 12 hours but have not received any response or further instructions.
I need this dataset for my research work, so any assistance would be greatly appreciated.

**Comment by hmorimitsu** [comment]
Hi, I'm sorry but I have no connection to the Sintel website. I cannot help you with this issue. You should still try to contact the maintainers of that website.

**Comment by cppppp** [comment]
> I am encountering issues while trying to register an account for the MPI Sintel dataset. I have followed the website's instructions and sent an email containing my full name and affiliation to [sintel@tue.mpg.de](mailto:sintel@tue.mpg.de), but it has been over 12 hours and I still cannot access or download the dataset.
> 
> Here are the detailed steps I have taken to register:
> 
> I visited the official website of the MPI Sintel dataset: http://sintel.is.tue.mpg.de/. I checked my email address and domain to confirm they were not enabled. I sent an email as instructed by the website, including my full name and affiliation, to [sintel@tue.mpg.de](mailto:sintel@tue.mpg.de). I have waited for more than 12 hours but have not received any response or further instructions. I need this dataset for my research work, so any assistance would be greatly appreciated.

Hello, fangfang11-plog, I am also encountering this problem. Are you interested in communicating about this? Thank you very much!

**Comment by cppppp** [comment]
> Try e-mailing not the sintel website, but the lab that maintains the benchmark directly:
> 
> [ps-admin@tuebingen.mpg.de](mailto:ps-admin@tuebingen.mpg.de)
> 
> This should be much faster.

Thanks very much!
