### ISSUE TITLE
RPKNet inference time?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [hmorimitsu/ptlflow#81]
Would you expect "RPKNet things" to run faster on a pair of images vs "GMflow things" given that RPKNet's pretrained weights are only 11mb and GMflow is 17mb?  That's not the case for me.   GMflow runs at  1.35s/it]S, while RPKNet is a much slower 1.73s/it]S.  Is this expected??  I thought the whole point of RPKNet was that it only had 2m parameters making very fast?

**Comment by hmorimitsu** [comment]
Hi, thanks for the question. 

RPKNet is not faster than GMFlow, and you can see a comparison of the running speeds of multiple models in the docs: https://ptlflow.readthedocs.io/en/latest/results/model_benchmark.html

Running speed is not directly correlated to model size or the number of operations. It varies greatly depending on how PyTorch, CUDA, GPU, etc., handles each operation. Some operations, such as self-attention, may require more memory and computations. However, they are heavily optimized in current DL pipelines, which makes them run faster.

RPKNet is small, but it has some speed bottlenecks: (1) it uses large convolution kernels, which usually are not well optimized, and (2) it uses a convolution block with many sequential operations, which reduces parallelization. If you are interested, you can find more information in the paper.

Best.

**Comment by noobtoob4lyfe** [comment]
Thank you!  very helpful.
